from playwright.sync_api import Page, expect
import pytest
@pytest.mark.order(1)
def test_rutube_catalog(page: Page):
    page.goto('https://rutube.ru')
    page.get_by_role('link', name= 'Каталог').click()
    expect(page.get_by_role("link", name="RUTUBE x PREMIER RUTUBE x")).to_be_visible()
    expect(page.get_by_role("link", name="Авто Авто")).to_be_visible()
    expect(page.get_by_role("link", name="Анимация Анимация")).to_be_visible()
    expect(page.get_by_role("link", name="Аниме Аниме")).to_be_visible()
    expect(page.get_by_role("link", name="Блогеры Блогеры")).to_be_visible()
    expect(page.get_by_role("link", name="Видеоигры Видеоигры")).to_be_visible()
    expect(page.get_by_role("link", name="Детям Детям")).to_be_visible()
    expect(page.get_by_role("link", name="Еда Еда")).to_be_visible()
    expect(page.get_by_role("link", name="Интервью Интервью")).to_be_visible()
    expect(page.get_by_role("link", name="Культура Культура")).to_be_visible()
    expect(page.get_by_role("link", name="Лайфхаки Лайфхаки")).to_be_visible()
    expect(page.get_by_role("link", name="Музыка Музыка")).to_be_visible()
    expect(page.get_by_role("link", name="Новости и СМИ Новости и СМИ")).to_be_visible()
    expect(page.get_by_role("link", name="Обучение Обучение")).to_be_visible()
    expect(page.get_by_role("link", name="Подкасты Подкасты")).to_be_visible()
    expect(page.get_by_role("link", name="Путешествия Путешествия")).to_be_visible()
    expect(page.get_by_role("link", name="Радио Радио")).to_be_visible()
    expect(page.get_by_role("link", name="Сельское хозяйство Сельское хозяйство")).to_be_visible()
    expect(page.get_by_role("link", name="Сериалы Сериалы")).to_be_visible()
    expect(page.get_by_role("link", name="Спорт Спорт")).to_be_visible()
    expect(page.get_by_role("link", name="ТВ онлайн ТВ онлайн")).to_be_visible()
    expect(page.get_by_role("link", name="Телешоу Телешоу")).to_be_visible()
    expect(page.get_by_role("link", name="Трансляции Трансляции")).to_be_visible()
    expect(page.get_by_role("link", name="Фильмы Фильмы")).to_be_visible()
    expect(page.get_by_role("link", name="Фонды помощи Фонды помощи")).to_be_visible()
    expect(page.get_by_role("link", name="Футбол Футбол")).to_be_visible()
    expect(page.get_by_role("link", name="Юмор Юмор")).to_be_visible()


